[build]
  # Install and build frontend
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "functions"

[dev]
  # Start the frontend dev server (use netlify dev for local functions emulation)
  command = "npm run dev --prefix frontend"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
