[build]
  # Install both frontend and functions deps, then build the frontend
  command = "npm run install:all && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "functions"

[dev]
  # Start the frontend dev server (use netlify dev for local functions emulation)
  command = "npm run dev --prefix frontend"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
