[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"

[context.production.environment]
  NODE_VERSION = "18"

[plugins]
  # Add Netlify plugins here if desired

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
